@startuml car_rental-erd

skinparam linetype polyline

entity "users" as u {
    user_id : uuid <<K>>
    name : text
    email : text
}

entity "user_emails" as ue {
    email : text <<K>>
    user_id : uuid
}

entity "rents" as r {
    rent_id : uuid <<K>>
    user_id : uuid
    car_id : uuid
    start_date : timestamp
    end_date : timestamp
}

entity "cars" as c {
    car_id : uuid <<K>>
    make : text
    model : text
    year : int
}

entity "user_rents" as ur {
    user_id : uuid <<K>>
    rent_id : uuid <<C Desc>>
    amount : double,
    rent_type : text
}

entity "user_cars" as uc {
    user_id : uuid <<K>>
    rent_id : uuid <<C Desc>>
    car_id : uuid,
    car_number : text,
    car_type : text
}

u ||--o{ ur : has >
ur }o--|| r : is >
c ||--o{ r : is rented in >
u ||--o{ uc : has >
uc }o--|| c : is owned by >
u ||--|| ue : email linked to >
ue ||--o{ uc : has cars >

@enduml
